#! /bin/bash

#use WINE to install refprop.exe in the C:\Program Files\REFPROP\ directory
#execute this binery file, need to have the following installed on Linux:
#	gfortran
#	sed
#	dos2unix
#use the refprop.py interface to call the librefprop.so

#define standard path where the original refprop files will be stored
path='/usr/local/lib/refprop/'

#delete previous trail
sudo rm -rf ${path}
sudo rm -f ${path%refprop/}librefprop*

#create directories
sudo mkdir -p ${path}FOR/
sudo mkdir -p ${path}fluids/
sudo mkdir -p ${path}mixtures/

#copy fortran / refprop files to ${path}
sudo cp -r ~/.wine/drive_c/Program\ Files/REFPROP/fortran/*.FOR ${path}FOR/
sudo cp -r ~/.wine/drive_c/Program\ Files/REFPROP/fluids/* ${path}fluids/
sudo cp -r ~/.wine/drive_c/Program\ Files/REFPROP/mixtures/* ${path}mixtures/

#allow read permission all
sudo chmod -R a+r ${path}fluids/
sudo chmod -R a+r ${path}mixtures/

#rename all filenames to UPPERCASE
echo 'rename lowercase to UPPERCASE filenames'
cd ${path}fluids/
sudo rename 'y/a-z/A-Z/' *
cd ${path}mixtures/
sudo rename 'y/a-z/A-Z/' *

#modify PASS_FTN.FOR
#remove windows specific command
sudo sed -i 's/      dll_export/c     dll_export/' ${path}FOR/PASS_FTN.FOR

#process files (dos to unix)
for files in ${path}FOR/*.FOR ${path}fluids/* ${path}mixtures/*
do
	{
	echo "processing ${files}"
	#change *.FOR files from dos to unix
	sudo dos2unix -q ${files}
	} &
done
#wait for multiprocessing to complete
wait

#create object file
echo 'create object files'
sudo mkdir -p /tmp/refprop/object
cd /tmp/refprop/object
sudo gfortran -fpic -c -g ${path}FOR/*.FOR

#create the dynamically link "shared objects" (so) library
echo 'create shared object file'
sudo gfortran -shared -Wl,-soname,librefprop.so.9 -o ${path}librefprop.so.9.0 /tmp/refprop/object/*.o -lc

#delete object files
cd ~
sudo rm -rf /tmp/refprop/

#install the object file
echo 'install object file'
sudo ldconfig -n ${path%/}
sudo ln -s ${path}librefprop.so.9 ${path%refprop/}librefprop.so

#display ported commands
#nm ${path}librefprop.so

